openapi: 3.0.0
info:
  title: Subscription Manager
  version: 1.0.0
paths:
  /subscribe:
    post:
      operationId: subscription_routes.subscribe
      summary: Create a new subscription
      description: |
        Create a new subscription to an event. If the event is already occuring, for example the machine of interest is already available, return a message stating as such.

        event_key, often, will be VILLAGE.HALL.TYPE.NAME
      parameters:
        - name: event_key
          in: query
          description: Key representing the type of event
          required: true
          schema:
            type: string
        - name: fulfillment
          in: query
          description: How the subscription is fulfilled
          required: true
          schema:
            type: string
            enum: ["discord", "sms"]
        - name: user
          in: query
          description: |
            How to identify the subscriber (phone number, discord ID, etc)
          required: true
          schema:
            type: string
      responses:
        201:
          description: Subscription created
          content:
            text/plain:
              schema:
                type: string
                example: You will be notified when the machine is ready
        202:
          description: |
            Successful request, but the requested resource is already available.
          content:
            text/plain:
              schema:
                type: string
                example: That machine is already available
