{
 "title": "Laundry Dashboard",
 "time": { "from": "now-90m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "hall", "label": "Residence Hall", "query": { "query": "label_values(hall)" } },
   { "name": "type", "label": "Machine Type", "query": { "query": "label_values(type)" } }
  ]
 },
 "panels": [
  {
   "title": "Machines Available",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laundry_availability{hall=\"$hall\", type=~\"$type\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Time Remaining per Machine",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{hall=\"$hall\", __name__=\"machine_time\"}",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Machine Availability",
   "type": "timeseries",
   "description": "Quantity of machines available in selected residence hall",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "laundry_availability{hall=\"$hall\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Machine Time Remaining",
   "type": "timeseries",
   "description": "Time remaining (in minutes) in each machine in selected residence hall. If a machine is available, it has a value of zero.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "machine_time{hall=\"$hall\", type=~\"$type\"}",
     "legendFormat": "{{type}} {{name}}"
    }
   ]
  }
 ]
}